export default function getRegionCountriesName() {
    // SouthernAfrica=[
    //     {"label": "Lesotho", "value": "lesotho"},
    //     {"label": "Swaziland", "value": "swaziland"},
    //     {"label": "Botswana", "value": "botswana"},
    //     {"label": "Namibia", "value": "namibia"},
    //     {"label": "South Africa", "value": "south_africa"}
    // ],
    // MiddleAfrica=[
    //     {"label": "Angola", "value": "angola"},
    //     {"label": "Cameroon", "value": "cameroon"},
    //     {"label": "Equatorial Guinea", "value": "equatorial_guinea"},
    //     {"label": "Gabon", "value": "gabon"},
    //     {"label": "Congo", "value": "congo"},
    //     {"label": "Chad", "value": "chad"},
    //     {"label": "Central African Republic", "value": "central_african_republic"},
    //     {"label": "Congo, the Democratic Republic", "value": "congo_dr"},
    //     {"label": "Sao Tome and Principe", "value": "sao_tome_and_principe"}
    // ]
    // EasternAfrica=[
    //     {"label": "Burundi", "value": "burundi"},
    //     {"label": "Eritrea", "value": "eritrea"},
    //     {"label": "Madagascar", "value": "madagascar"},
    //     {"label": "Reunion", "value": "reunion"},
    //     {"label": "Somalia", "value": "somalia"},
    //     {"label": "Comoros", "value": "comoros"},
    //     {"label": "Ethiopia", "value": "ethiopia"},
    //     {"label": "Rwanda", "value": "rwanda"},
    //     {"label": "Djibouti", "value": "djibouti"},
    //     {"label": "Kenya", "value": "kenya"},
    //     {"label": "Mayotte", "value": "mayotte"},
    //     {"label": "Seychelles", "value": "seychelles"},
    //     {"label": "Uganda", "value": "uganda"},
    //     {"label": "Mozambique", "value": "mozambique"},
    //     {"label": "Zambia", "value": "zambia"},
    //     {"label": "Malawi", "value": "malawi"},
    //     {"label": "Tanzania", "value": "tanzania"},
    //     {"label": "Zimbabwe", "value": "zimbabwe"}
    // ]
    // WesternAfrica=[
    //     {"label": "Benin", "value": "benin"},
    //     {"label": "Liberia", "value": "liberia"},
    //     {"label": "Saint Helena", "value": "saint_helena"},
    //     {"label": "Burkina Faso", "value": "burkina_faso"},
    //     {"label": "Gambia", "value": "gambia"},
    //     {"label": "Mali", "value": "mali"},
    //     {"label": "Ghana", "value": "ghana"},
    //     {"label": "Mauritania", "value": "mauritania"},
    //     {"label": "Senegal", "value": "senegal"},
    //     {"label": "Cape Verde", "value": "cape_verde"},
    //     {"label": "Cote D'ivoire", "value": "cote_divoire"},
    //     {"label": "Guinea", "value": "guinea"},
    //     {"label": "Niger", "value": "niger"},
    //     {"label": "Sierra Leone", "value": "sierra_leone"},
    //     {"label": "Guinea-Bissau", "value": "guinea_bissau"},
    //     {"label": "Nigeria", "value": "nigeria"},
    //     {"label": "Togo", "value": "togo"}
    // ]
    // NorthernAfrica=[
    //     {"label": "Algeria", "value": "algeria"},
    //     {"label": "Egypt", "value": "egypt"},
    //     {"label": "Libyan Arab Jamahiriya", "value": "libya"},
    //     {"label": "Morocco", "value": "morocco"},
    //     {"label": "Tunisia", "value": "tunisia"},
    //     {"label": "Western Sahara", "value": "western_sahara"},
    //     {"label": "Sudan", "value": "sudan"}
    // ]
//     let SouthAmerica=[
//       {"name": "Brazil", "id": "brazil"},
//       {"name": "Argentina", "id": "argentina"},
//       {"name": "Colombia", "id": "colombia"},
//       {"name": "Peru", "id": "peru"},
//       {"name": "Chile", "id": "chile"}
//   ]
  
//   let Africa=[
//       {"name": "Nigeria", "id": "nigeria"},
//       {"name": "Egypt", "id": "egypt"},
//       {"name": "South Africa", "id": "south_africa"},
//       {"name": "Kenya", "id": "kenya"},
//       {"name": "Ethiopia", "id": "ethiopia"}
//   ]
//   let Oceania=[
//       {"name": "Australia", "id": "australia"},
//       {"name": "New Zealand", "id": "new_zealand"},
//       {"name": "Papua New Guinea", "id": "papua_new_guinea"},
//       {"name": "Fiji", "id": "fiji"},
//       {"name": "Solomon Islands", "id": "solomon_islands"}
//   ]
//   let NorthAmerica=[
//       {"name": "United States", "id": "united_states"},
//       {"name": "Canada", "id": "canada"},
//       {"name": "Mexico", "id": "mexico"},
//       {"name": "Guatemala", "id": "guatemala"},
//       {"name": "Costa Rica", "id": "costa_rica"},
//       {"name": "Cuba", "id": "cuba"},
//       {"name": "Jamaica", "id": "jamaica"},
//       {"name": "Haiti", "id": "haiti"},
//       {"name": "Dominican Republic", "id": "dominican_republic"},
//       {"name": "Panama", "id": "panama"}
//   ]
  
//   let Asia=[
//       {"name": "China", "id": "china"},
//       {"name": "India", "id": "india"},
//       {"name": "Japan", "id": "japan"},
//       {"name": "South Korea", "id": "south_korea"},
//       {"name": "Indonesia", "id": "indonesia"},
//       {"name": "Vietnam", "id": "vietnam"},
//       {"name": "Thailand", "id": "thailand"},
//       {"name": "Malaysia", "id": "malaysia"},
//       {"name": "Philippines", "id": "philippines"},
//       {"name": "Singapore", "id": "singapore"}
//   ]
//   let Europe=[
//       {"name": "United Kingdom", "id": "united_kingdom"},
//       {"name": "France", "id": "france"},
//       {"name": "Germany", "id": "germany"},
//       {"name": "Spain", "id": "spain"},
//       {"name": "Italy", "id": "italy"},
//       {"name": "Netherlands", "id": "netherlands"},
//       {"name": "Switzerland", "id": "switzerland"},
//       {"name": "Sweden", "id": "sweden"},
//       {"name": "Poland", "id": "poland"},
//       {"name": "Austria", "id": "austria"}
//   ]
  


// rounak changes

let SouthAmerica=[
    {"name": "Argentina", "id": "argentina"},
    {"name": "Bolivia", "id": "bolivia"},
    {"name": "Brazil", "id": "brazil"},
    {"name": "Chile", "id": "chile"},
    {"name": "Colombia", "id": "colombia"},
    {"name": "Ecuador", "id": "ecuador"},
    {"name": "Guyana", "id": "guyana"},
    {"name": "Paraguay", "id": "paraguay"},
    {"name": "Peru", "id": "peru"},
    {"name": "Suriname", "id": "suriname"},
    {"name": "Uruguay", "id": "uruguay"},
    {"name": "Venezuela", "id": "venezuela"}
]

let Africa=[
    {"name": "Algeria", "id": "algeria"},
    {"name": "Angola", "id": "angola"},
    {"name": "Benin", "id": "benin"},
    {"name": "Botswana", "id": "botswana"},
    {"name": "Burkina Faso", "id": "burkina_faso"},
    {"name": "Burundi", "id": "burundi"},
    {"name": "Cabo Verde", "id": "cabo_verde"},
    {"name": "Cameroon", "id": "cameroon"},
    {"name": "Central African Republic", "id": "central_african_republic"},
    {"name": "Chad", "id": "chad"},
    {"name": "Comoros", "id": "comoros"},
    {"name": "Congo (Congo-Brazzaville)", "id": "congo"},
    {"name": "Democratic Republic of the Congo", "id": "democratic_republic_of_the_congo"},
    {"name": "Djibouti", "id": "djibouti"},
    {"name": "Egypt", "id": "egypt"},
    {"name": "Equatorial Guinea", "id": "equatorial_guinea"},
    {"name": "Eritrea", "id": "eritrea"},
    {"name": "Eswatini (Swaziland)", "id": "eswatini"},
    {"name": "Ethiopia", "id": "ethiopia"},
    {"name": "Gabon", "id": "gabon"},
    {"name": "Gambia", "id": "gambia"},
    {"name": "Ghana", "id": "ghana"},
    {"name": "Guinea", "id": "guinea"},
    {"name": "Guinea-Bissau", "id": "guinea_bissau"},
    {"name": "Ivory Coast", "id": "ivory_coast"},
    {"name": "Kenya", "id": "kenya"},
    {"name": "Lesotho", "id": "lesotho"},
    {"name": "Liberia", "id": "liberia"},
    {"name": "Libya", "id": "libya"},
    {"name": "Madagascar", "id": "madagascar"},
    {"name": "Malawi", "id": "malawi"},
    {"name": "Mali", "id": "mali"},
    {"name": "Mauritania", "id": "mauritania"},
    {"name": "Mauritius", "id": "mauritius"},
    {"name": "Morocco", "id": "morocco"},
    {"name": "Mozambique", "id": "mozambique"},
    {"name": "Namibia", "id": "namibia"},
    {"name": "Niger", "id": "niger"},
    {"name": "Nigeria", "id": "nigeria"},
    {"name": "Rwanda", "id": "rwanda"},
    {"name": "São Tomé and Príncipe", "id": "sao_tome_and_principe"},
    {"name": "Senegal", "id": "senegal"},
    {"name": "Seychelles", "id": "seychelles"},
    {"name": "Sierra Leone", "id": "sierra_leone"},
    {"name": "Somalia", "id": "somalia"},
    {"name": "South Africa", "id": "south_africa"},
    {"name": "South Sudan", "id": "south_sudan"},
    {"name": "Sudan", "id": "sudan"},
    {"name": "Tanzania", "id": "tanzania"},
    {"name": "Togo", "id": "togo"},
    {"name": "Tunisia", "id": "tunisia"},
    {"name": "Uganda", "id": "uganda"},
    {"name": "Zambia", "id": "zambia"},
    {"name": "Zimbabwe", "id": "zimbabwe"}
]
let Oceania=[
    {"name": "Australia", "id": "australia"},
    {"name": "Fiji", "id": "fiji"},
    {"name": "Kiribati", "id": "kiribati"},
    {"name": "Marshall Islands", "id": "marshall_islands"},
    {"name": "Micronesia", "id": "micronesia"},
    {"name": "Nauru", "id": "nauru"},
    {"name": "New Zealand", "id": "new_zealand"},
    {"name": "Palau", "id": "palau"},
    {"name": "Papua New Guinea", "id": "papua_new_guinea"},
    {"name": "Samoa", "id": "samoa"},
    {"name": "Solomon Islands", "id": "solomon_islands"},
    {"name": "Tonga", "id": "tonga"},
    {"name": "Tuvalu", "id": "tuvalu"},
    {"name": "Vanuatu", "id": "vanuatu"}
]
let NorthAmerica=[
    {"name": "Antigua and Barbuda", "id": "antigua_and_barbuda"},
    {"name": "Bahamas", "id": "bahamas"},
    {"name": "Barbados", "id": "barbados"},
    {"name": "Belize", "id": "belize"},
    {"name": "Canada", "id": "canada"},
    {"name": "Costa Rica", "id": "costa_rica"},
    {"name": "Cuba", "id": "cuba"},
    {"name": "Dominica", "id": "dominica"},
    {"name": "Dominican Republic", "id": "dominican_republic"},
    {"name": "El Salvador", "id": "el_salvador"},
    {"name": "Grenada", "id": "grenada"},
    {"name": "Guatemala", "id": "guatemala"},
    {"name": "Haiti", "id": "haiti"},
    {"name": "Honduras", "id": "honduras"},
    {"name": "Jamaica", "id": "jamaica"},
    {"name": "Mexico", "id": "mexico"},
    {"name": "Nicaragua", "id": "nicaragua"},
    {"name": "Panama", "id": "panama"},
    {"name": "Saint Kitts and Nevis", "id": "saint_kitts_and_nevis"},
    {"name": "Saint Lucia", "id": "saint_lucia"},
    {"name": "Saint Vincent and the Grenadines", "id": "saint_vincent_and_the_grenadines"},
    {"name": "Trinidad and Tobago", "id": "trinidad_and_tobago"},
    {"name": "United States", "id": "united_states"}
]

let Asia=[
    {"name": "Afghanistan", "id": "afghanistan"},
    {"name": "Armenia", "id": "armenia"},
    {"name": "Azerbaijan", "id": "azerbaijan"},
    {"name": "Bahrain", "id": "bahrain"},
    {"name": "Bangladesh", "id": "bangladesh"},
    {"name": "Bhutan", "id": "bhutan"},
    {"name": "Brunei", "id": "brunei"},
    {"name": "Cambodia", "id": "cambodia"},
    {"name": "China", "id": "china"},
    {"name": "Cyprus", "id": "cyprus"},
    {"name": "Georgia", "id": "georgia"},
    {"name": "India", "id": "india"},
    {"name": "Indonesia", "id": "indonesia"},
    {"name": "Iran", "id": "iran"},
    {"name": "Iraq", "id": "iraq"},
    {"name": "Israel", "id": "israel"},
    {"name": "Japan", "id": "japan"},
    {"name": "Jordan", "id": "jordan"},
    {"name": "Kazakhstan", "id": "kazakhstan"},
    {"name": "Kuwait", "id": "kuwait"},
    {"name": "Kyrgyzstan", "id": "kyrgyzstan"},
    {"name": "Laos", "id": "laos"},
    {"name": "Lebanon", "id": "lebanon"},
    {"name": "Malaysia", "id": "malaysia"},
    {"name": "Maldives", "id": "maldives"},
    {"name": "Mongolia", "id": "mongolia"},
    {"name": "Myanmar", "id": "myanmar"},
    {"name": "Nepal", "id": "nepal"},
    {"name": "North Korea", "id": "north_korea"},
    {"name": "Oman", "id": "oman"},
    {"name": "Pakistan", "id": "pakistan"},
    {"name": "Palestine", "id": "palestine"},
    {"name": "Philippines", "id": "philippines"},
    {"name": "Qatar", "id": "qatar"},
    {"name": "Russia", "id": "russia"},
    {"name": "Saudi Arabia", "id": "saudi_arabia"},
    {"name": "Singapore", "id": "singapore"},
    {"name": "South Korea", "id": "south_korea"},
    {"name": "Sri Lanka", "id": "sri_lanka"},
    {"name": "Syria", "id": "syria"},
    {"name": "Taiwan", "id": "taiwan"},
    {"name": "Tajikistan", "id": "tajikistan"},
    {"name": "Thailand", "id": "thailand"},
    {"name": "Timor-Leste", "id": "timor_leste"},
    {"name": "Turkey", "id": "turkey"},
    {"name": "Turkmenistan", "id": "turkmenistan"},
    {"name": "United Arab Emirates", "id": "united_arab_emirates"},
    {"name": "Uzbekistan", "id": "uzbekistan"},
    {"name": "Vietnam", "id": "vietnam"},
    {"name": "Yemen", "id": "yemen"}
]
let Europe=[
    {"name": "Albania", "id": "albania"},
    {"name": "Andorra", "id": "andorra"},
    {"name": "Austria", "id": "austria"},
    {"name": "Belarus", "id": "belarus"},
    {"name": "Belgium", "id": "belgium"},
    {"name": "Bosnia and Herzegovina", "id": "bosnia_and_herzegovina"},
    {"name": "Bulgaria", "id": "bulgaria"},
    {"name": "Croatia", "id": "croatia"},
    {"name": "Cyprus", "id": "cyprus"},
    {"name": "Czech Republic", "id": "czech_republic"},
    {"name": "Denmark", "id": "denmark"},
    {"name": "Estonia", "id": "estonia"},
    {"name": "Finland", "id": "finland"},
    {"name": "France", "id": "france"},
    {"name": "Germany", "id": "germany"},
    {"name": "Greece", "id": "greece"},
    {"name": "Hungary", "id": "hungary"},
    {"name": "Iceland", "id": "iceland"},
    {"name": "Ireland", "id": "ireland"},
    {"name": "Italy", "id": "italy"},
    {"name": "Kosovo", "id": "kosovo"},
    {"name": "Latvia", "id": "latvia"},
    {"name": "Liechtenstein", "id": "liechtenstein"},
    {"name": "Lithuania", "id": "lithuania"},
    {"name": "Luxembourg", "id": "luxembourg"},
    {"name": "Malta", "id": "malta"},
    {"name": "Moldova", "id": "moldova"},
    {"name": "Monaco", "id": "monaco"},
    {"name": "Montenegro", "id": "montenegro"},
    {"name": "Netherlands", "id": "netherlands"},
    {"name": "North Macedonia", "id": "north_macedonia"},
    {"name": "Norway", "id": "norway"},
    {"name": "Poland", "id": "poland"},
    {"name": "Portugal", "id": "portugal"},
    {"name": "Romania", "id": "romania"},
    {"name": "Russia", "id": "russia"},
    {"name": "San Marino", "id": "san_marino"},
    {"name": "Serbia", "id": "serbia"},
    {"name": "Slovakia", "id": "slovakia"},
    {"name": "Slovenia", "id": "slovenia"},
    {"name": "Spain", "id": "spain"},
    {"name": "Sweden", "id": "sweden"},
    {"name": "Switzerland", "id": "switzerland"},
    {"name": "Ukraine", "id": "ukraine"},
    {"name": "United Kingdom", "id": "united_kingdom"},
    {"name": "Vatican City", "id": "vatican_city"}
]

     let Antartica=[]

      
    //   SouthernAfrica,NorthernAfrica,WesternAfrica,EasternAfrica,MiddleAfrica,
    return {
        SouthAmerica: SouthAmerica,
        Africa: Africa,
        Oceania: Oceania,
        NorthAmerica: NorthAmerica,
        Asia: Asia,
        Europe: Europe,
        Antartica: Antartica
    };
    
}