export default function getIndustryInterest() {
    const industryInterest = [
        { label: "Agriculture", value: "agriculture" },
        { label: "Renewable Energies", value: "renewable_energies" },
        { label: "Infrastructure", value: "infrastructure" },
        { label: "Fintech", value: "fintech" },
        { label: "Healthcare", value: "healthcare" },
        { label: "Information Technology", value: "information_technology" },
        { label: "Manufacturing", value: "manufacturing" },
        { label: "Automotive", value: "automotive" },
        { label: "Education", value: "education" },
        { label: "Real Estate", value: "real_estate" },
        { label: "Entertainment", value: "entertainment" },
        { label: "Telecommunications", value: "telecommunications" },
        { label: "Retail", value: "retail" },
        { label: "Transportation", value: "transportation" },
        { label: "Finance", value: "finance" },
        { label: "Travel and Tourism", value: "travel_and_tourism" },
        { label: "Food and Beverage", value: "food_and_beverage" },
        { label: "Environmental Services", value: "environmental_services" },
        { label: "Fashion and Apparel", value: "fashion_and_apparel" },
        { label: "Pharmaceuticals", value: "pharmaceuticals" },
        { label: "Biotechnology", value: "biotechnology" },
        { label: "Consulting", value: "consulting" },
        { label: "Internet of Things (IoT)", value: "iot" },
        { label: "Artificial Intelligence (AI)", value: "ai" },
        { label: "Blockchain", value: "blockchain" },
        { label: "Cybersecurity", value: "cybersecurity" },
        { label: "Gaming", value: "gaming" },
        { label: "Insurance", value: "insurance" },
        { label: "Legal Services", value: "legal_services" },
        { label: "Mining", value: "mining" },
        { label: "Oil and Gas", value: "oil_and_gas" },
        { label: "Shipping", value: "shipping" },
        { label: "Space Exploration", value: "space_exploration" },
        { label: "Defense", value: "defense" },
        { label: "Nonprofit and Philanthropy", value: "nonprofit_and_philanthropy" },
        { label: "Sports", value: "sports" },
        { label: "Market Research", value: "market_research" },
        { label: "Hospitality", value: "hospitality" },
        { label: "Utilities", value: "utilities" },
        { label: "Forestry", value: "forestry" },
        { label: "Waste Management", value: "waste_management" },
        // Add more industries as needed
    ];
    
    return industryInterest;
}