export default function getIndustryInterestMultiple() {
    const industryInterestMultiple = [
        { name: "Agriculture", id: "agriculture" },
        { name: "Renewable Energies", id: "renewable_energies" },
        { name: "Infrastructure", id: "infrastructure" },
        { name: "Fintech", id: "fintech" },
        { name: "Healthcare", id: "healthcare" },
        { name: "Information Technology", id: "information_technology" },
        { name: "Manufacturing", id: "manufacturing" },
        { name: "Automotive", id: "automotive" },
        { name: "Education", id: "education" },
        { name: "Real Estate", id: "real_estate" },
        { name: "Entertainment", id: "entertainment" },
        { name: "Telecommunications", id: "telecommunications" },
        { name: "Retail", id: "retail" },
        { name: "Transportation", id: "transportation" },
        { name: "Finance", id: "finance" },
        { name: "Travel and Tourism", id: "travel_and_tourism" },
        { name: "Food and Beverage", id: "food_and_beverage" },
        { name: "Environmental Services", id: "environmental_services" },
        { name: "Fashion and Apparel", id: "fashion_and_apparel" },
        { name: "Pharmaceuticals", id: "pharmaceuticals" },
        { name: "Biotechnology", id: "biotechnology" },
        { name: "Consulting", id: "consulting" },
        { name: "Internet of Things (IoT)", id: "iot" },
        { name: "Artificial Intelligence (AI)", id: "ai" },
        { name: "Blockchain", id: "blockchain" },
        { name: "Cybersecurity", id: "cybersecurity" },
        { name: "Gaming", id: "gaming" },
        { name: "Insurance", id: "insurance" },
        { name: "Legal Services", id: "legal_services" },
        { name: "Mining", id: "mining" },
        { name: "Oil and Gas", id: "oil_and_gas" },
        { name: "Shipping", id: "shipping" },
        { name: "Space Exploration", id: "space_exploration" },
        { name: "Defense", id: "defense" },
        { name: "Nonprofit and Philanthropy", id: "nonprofit_and_philanthropy" },
        { name: "Sports", id: "sports" },
        { name: "Market Research", id: "market_research" },
        { name: "Hospitality", id: "hospitality" },
        { name: "Utilities", id: "utilities" },
        { name: "Forestry", id: "forestry" },
        { name: "Waste Management", id: "waste_management" },
        // Add more industries as needed
    ]
    return industryInterestMultiple;
}