// import { color } from "html2canvas/dist/types/css/types/color";
import React from "react";
import ReactApexChart from "react-apexcharts";

const ColumnChart = () => {
  const chartData = {
    series: [
      {
        name: 'Net Profit',
        data: [44, 55, 57, 56, 61, 58, 63, 60, 66],
        color: '#ef7d30' // Custom color for Net Profit series
      },
      {
        name: 'Revenue',
        data: [76, 85, 101, 98, 87, 105, 91, 114, 94],
        color: '#00cabf' // Custom color for Revenue series
      },
      {
        name: 'Free Cash Flow',
        data: [35, 41, 36, 26, 45, 48, 52, 53, 41],
        color: '#1771e7' // Custom color for Free Cash Flow series
      }
    ],
    options: {
      chart: {
        type: 'bar',
        height: 320
      },
      plotOptions: {
        bar: {
          horizontal: false,
          columnWidth: '65%',
          endingShape: 'rounded'
        },
      },
      dataLabels: {
        enabled: false
      },
      stroke: {
        show: true,
        width: 1,
        colors: ['transparent']
      },
      xaxis: {
        categories: ['Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'],
      },
      yaxis: {
        title: {
          text: '$ (thousands)'
        }
      },
      fill: {
        opacity: 1
      },
      tooltip: {
        y: {
          formatter: function (val) {
            return "$ " + val + " thousands"
          }
        }
      }
    }
  };

  return (
    <div>
      <div id="chart" className="rounded-lg shadow-md bg-white">
      <h1 className="font-oxygen font-semibold text-center text-md pt-4">Revenue Generated By Portal</h1>
        <ReactApexChart options={chartData.options} series={chartData.series} type="bar" height={350} />
      </div>
      <div id="html-dist"></div>
    </div>
  );
};

export default ColumnChart;
